[package]
name = "compiler"
version = "0.1.0"
edition = "2021"

build = "build.rs"

[build-dependencies]
lalrpop = "*"
regex = "*"

[dependencies]
bumpalo = "3.13.0"
lalrpop-util = { version = "*", features = ["lexer", "unicode"] }
